name: Generate Podcasts XML
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: RBK93/podcastgenerator@main

        
        
